rediti/common/urls.py
from django.urls import path

from common.views import HomeView

app_name = "common"

urlpatterns = [
    path("", HomeView.as_view(), name="home")
]

rediti/rediti/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('', include('users.urls')),
    path('', include('subs.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rediti/subs/urls.py
from django.urls import path
from .views import SubredsView, SubredView

app_name= 'subs'

urlpatterns = [
 path('subs/', SubredsView.as_view(), name='subred'),
 path('subs/<slug:slug>/', SubredView.as_view(), name='subreds'),
  ]

rediti/users/urls.py
from .views import ProfileView, LogoutView, LoginView, SignupView
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path("signup/", SignupView.as_view(), name="signup"),
    path("user/<int:pk>/", ProfileView.as_view(), name="profile")
]

rediti/common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator

class IndexedTimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    

    class Meta:
        abstract = True

class VoteAbstractModel(models.Model):
    user = models.ForeignKey('users.user', on_delete=models.CASCADE)
    count = models.IntegerField(default=0,
        validators=[
            MaxValueValidator(1),
            MinValueValidator(0)
        ])

    class Meta:
        abstract = True

rediti/subs/models.py
from django.db import models
from common.models import IndexedTimeStampedModel


class Subred(models.Model):
    title = models.CharField(max_length=50)
    creator = models.ForeignKey("users.User", related_name="subreds", on_delete=models.CASCADE)
    description = models.TextField()
    slug = models.SlugField()

    def __str__(self):
        return self.title
    

class Thread(IndexedTimeStampedModel):
    title = models.CharField(max_length=50)
    author = models.ForeignKey("users.User", related_name="threads", on_delete=models.CASCADE)
    subred = models.ForeignKey('Subred', related_name="threads", on_delete=models.CASCADE)
    vote_count = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title
    
class Post(IndexedTimeStampedModel):
    content = models.TextField()
    author = models.ForeignKey("users.User", related_name="posts", on_delete=models.CASCADE)
    thread = models.ForeignKey('Thread', related_name="posts", on_delete=models.CASCADE)
    vote_count = models.IntegerField(default=0)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return ("{} - {} - {}").format(self.id, self.thread, self.author)


class Subscription(IndexedTimeStampedModel):
    user = models.ForeignKey('users.User', related_name="subscription", on_delete=models.CASCADE)
    sub = models.ForeignKey('Subred', related_name="subscription", on_delete=models.CASCADE)
    subscribed = models.BooleanField(default=False)

    class Meta:
        unique_together = [('user', 'sub')]

rediti/users/models.py
from .manager import UserManager
from common.models import IndexedTimeStampedModel
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models


class User(AbstractBaseUser, PermissionsMixin, IndexedTimeStampedModel):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    karma = models.IntegerField(default=0)
    avatar = models.ImageField(blank=True, default='avatar.jpg')
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.username
    

rediti/users/forms.py
from django import forms

from .models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Erro!!! Suas senhas não são iguais!"
            )

    def save(self, commit=True):
        raw_password = self.cleaned_data.get('password')
        self.instance.username = self.cleaned_data.get('username')
        self.instance.set_password(raw_password)
        self.instance.save()
        return self.instance

rediti/common/views.py
from django.shortcuts import render
from django.views import generic

class HomeView(generic.TemplateView):
    template_name = "common/home.html"

rediti/subs/views.py
from django.shortcuts import render
from django.views import generic
from .models import Subred, Thread, Post
# Create your views here.
class SubredsView(generic.ListView):
    model = Subred
    template_name = 'subs/subred.html'
    context_object_name = 'subreds'

class SubredView(generic.DetailView):
    template_name = 'subs/subreds.html'
    model = Subred

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     subscription, created = Subscription.objects.get_or_create(user=self.request.user, subrediti=self.object)
    #     context['subscribed'] = True if subscription.subscribed else False
    #     return context 

rediti/users/views.py
from django.shortcuts import render
from django.views import generic
from .models import User
from django.contrib import auth
from django.contrib.auth import views, get_user_model, authenticate
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import redirect

from .forms import UserForm
from .models import User

class ProfileView(generic.DetailView):
    template_name = "users/profile.html"
    model = User

class LogoutView(views.LogoutView):
    next_page = 'common:home'

class LoginView(views.LoginView):
    template_name = "users/login.html"
    success_url = reverse_lazy('common:home')
    redirect_authenticated_user = True 

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('common:home'))
        return super(LoginView, self).get(request)

class SignupView(generic.FormView):
    template_name = "users/signup.html"
    form_class = UserForm
    redirect_authenticated_user = True 
    model = get_user_model()

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('common:home'))
        return super(SignupView, self).get(request)

    def form_valid(self, form):
        self.object = form.save()
        user = authenticate(username=self.object.email, password=form.cleaned_data['password'])
        auth.login(self.request, user)

        return redirect('common:home')

rediti/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <title>Rediti</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div id="container">
        {% block body%}{%endblock%}
    </div>
    <footer>
        <span>Rediti feito nas férias de alto impacto</span>
    </footer>
</body>
</html>

rediti/templates/common/home.html
{% extends 'base.html' %}

{% block body %}
olares
{% endblock %}

rediti/templates/navbar.html
<div class="navbar">
    <a href=""><img> logo aqui</a>
    <div class="links-area">
        <ul class="links-list">
            <a href="{% url 'common:home' %}">
                <li>Home</li>
            </a>
            {% if user.is_authenticated %}
            <a href="{% url 'users:profile' user.pk %}">
                <li>Profile</li>
            </a>
            <a href="{% url 'users:logout' %}">
                <li>Logout</li>
            </a>
            {% else %}
            <li>vai logar vagabundo</li>
            <a href="{% url 'users:login' %}">
                <li>Login</li>
            </a>
            {% endif %}
            <a href="{% url 'subs:subred' %}">
                <li>Subs</li>
            </a>
        </ul>
    </div>
</div>

rediti/templates/subs/subred.html
{% extends 'base.html' %}
{% block body %}
<span>Subs</span>
<div id="container">
    {% for subred in subreds %}
    <div class=>
        <div>
            <h4><a href="{% url 'subs:subreds' subred.slug %}">{{ subred.title }}</a></h4>
            <div>{{ subred.description }}</div>
        </div>
    </div>
    {% empty %}
    galera não sabe escrever
    {% endfor %}
</div>
{% endblock body %}

rediti/templates/subs/subreds.html
{% extends "base.html" %}

{% block body %}
    {% for thread in subreds.threads.all %}
    {{ thread.title }}
    {{ thread.author }}
    {{ thread.creator }}
    {% empty %}
    Galera tá com preguiça
    {% endfor %}

{% endblock body %}
    

rediti/templates/users/login.html
{% extends 'base.html' %}
{% block body %}
<form class="auth-form" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form.non_field_errors }} {% for field in form %}
        <div>
            {{ field.label_tag }} {{ field }} {{ field.errors }}
        </div>
        {% endfor %}
        <button type="submit">Login</button>
    </fieldset>
    <a href="">Não tem uma conta? Crie uma aqui :)</a>
</form>
{% endblock %}

rediti/templates/users/profile.html
{% extends 'base.html' %}

{% block body %}
dale boy
<div id="user">

    <p>username: {{ user.username }}</p>
    <p>email: {{ user.email }}</p>
    <p>karma: {{ user.karma }}</p>
    <p>avatar:</p> <img src="{{ user.avatar.url}}">
</div>

<div id="thread">
    <span>
        <h2>Threads</h2>
    </span>

    {% for thread in user.threads.all %}
    <div id="thread">
        <div id="karma"> {{ thread.vote_count }}</div>
        <span>{{ thread.title }}</span>
        by <a href="{% url 'users:profile' thread.author.pk %}">
            {{ thread.author }}
        </a> in
        <a href="">{{ thread.subrediti }}</a>
        <div>{{ post.content}}</div>
    </div>
    {% empty %}
    O carinha n sabe digitar
    {% endfor %}
</div>

</div>

<div id="Posts">
    <span>
        <h2>Posts</h2>
    </span>
    {% for post in user.posts.all %}
    <div id="thread">
        <div id="karma"> {{ posts.vote_count }}</div>
        <span>{{ posts.title }}</span>
        by <a href="{% url 'users:profile' posts.author.pk %}">
            {{ posts.author }}
        </a> in
        <a href="">{{ posts.subrediti }}</a>
        <div>{{ post.content}}</div>
    </div>
    {% empty %}
    O carinha n sabe digitar
    {% endfor %}

</div>
{% endblock %}

rediti/templates/users/signup.html
{% extends 'base.html' %}
{% block body %}
<form class='auth-form' method="post">
    {% csrf_token %}
    <fieldset>
        {{ form.non_field_errors }} {% for field in form %}
        <div>
            {{ field.label_tag }} {{ field }} {{ field.errors }}
        </div>
        {% endfor %}
        <button type="submit">Sign up</button>
    </fieldset>
    <a href="{% url 'users:login' %}">Já tem uma conta? Log in!</a>
</form>
{% endblock %}